import { parsePayload } from '../engine/parsers';
import { ommToTle, tleChecksum } from '../engine/parsers/tle-parser';
import { ISS_OMM, ISS_TLE } from './fixtures/orbital';

type Rec = Record<string, unknown>;
const recs = (r: unknown[]): Rec[] => r as Rec[];

describe('CSV options (parser.csv)', () => {
  it('keeps the default header behavior without a csv block', () => {
    const r = recs(parsePayload('a,b\n1,2\n', 'csv'));
    expect(r).toEqual([{ a: '1', b: '2' }]);
  });

  it('supports a custom delimiter, skip_lines and comment_prefix', () => {
    const body =
      'Generated by X\nsecond banner\n# comment\nname;lat\n  # indented comment\nA;1.5\n\nB;2\n';
    const r = recs(
      parsePayload(body, 'csv', undefined, undefined, {
        csv: { delimiter: ';', skip_lines: 2, comment_prefix: '#' }
      })
    );
    expect(r).toEqual([
      { name: 'A', lat: '1.5' },
      { name: 'B', lat: '2' }
    ]);
  });

  it('supports whitespace-delimited files without a header (c0..cN)', () => {
    const body = '  10.5   20.25  station-a\n11 21\tstation-b\n';
    const r = recs(
      parsePayload(body, 'csv', undefined, undefined, {
        csv: { delimiter: 'whitespace', has_header: false }
      })
    );
    expect(r).toEqual([
      { c0: '10.5', c1: '20.25', c2: 'station-a' },
      { c0: '11', c1: '21', c2: 'station-b' }
    ]);
  });

  it('names header-less columns from `columns`, extras fall back to cN', () => {
    const r = recs(
      parsePayload('1,2,3\n', 'csv', undefined, undefined, {
        csv: { has_header: false, columns: ['lat', 'lon'] }
      })
    );
    expect(r).toEqual([{ lat: '1', lon: '2', c2: '3' }]);
  });

  it('lets `columns` override an existing header row', () => {
    const r = recs(
      parsePayload('x|y\n1|2\n', 'csv', undefined, undefined, {
        csv: { delimiter: '|', columns: ['lat', 'lon'] }
      })
    );
    expect(r).toEqual([{ lat: '1', lon: '2' }]);
  });

  it('accepts a literal "\\t" delimiter', () => {
    const r = recs(
      parsePayload('a\tb\n1\t2\n', 'csv', undefined, undefined, { csv: { delimiter: '\\t' } })
    );
    expect(r).toEqual([{ a: '1', b: '2' }]);
  });
});

describe('JSON reshaping', () => {
  it('object_to_records turns a keyed map into records with _key', () => {
    const body = JSON.stringify({ data: { KJFK: { lat: 40 }, EGLL: { lat: 51 }, X: 5 } });
    const r = recs(parsePayload(body, 'json', 'data', undefined, { object_to_records: true }));
    expect(r).toEqual([
      { lat: 40, _key: 'KJFK' },
      { lat: 51, _key: 'EGLL' },
      { _key: 'X', value: 5 }
    ]);
  });

  it('honors a custom key_field', () => {
    const r = recs(
      parsePayload(JSON.stringify({ a: { v: 1 } }), 'json', undefined, undefined, {
        object_to_records: true,
        key_field: 'icao'
      })
    );
    expect(r).toEqual([{ v: 1, icao: 'a' }]);
  });

  it('array_columns maps array-of-array rows to objects', () => {
    const body = JSON.stringify({ time: 1, states: [['abc', 'UAL1 ', 1.5, 2.5, 'extra']] });
    const r = recs(
      parsePayload(body, 'json', 'states', undefined, {
        array_columns: ['icao24', 'callsign', 'lon', 'lat']
      })
    );
    expect(r).toEqual([{ icao24: 'abc', callsign: 'UAL1 ', lon: 1.5, lat: 2.5, c4: 'extra' }]);
  });

  it('array_columns: header uses the first row as column names', () => {
    const body = JSON.stringify([
      ['id', 'lat', 'lon'],
      [1, 10, 20],
      [2, 11, 21]
    ]);
    const r = recs(parsePayload(body, 'json', undefined, undefined, { array_columns: 'header' }));
    expect(r).toEqual([
      { id: 1, lat: 10, lon: 20 },
      { id: 2, lat: 11, lon: 21 }
    ]);
  });

  it('applies max_records after reshaping', () => {
    const body = JSON.stringify({ a: {}, b: {}, c: {} });
    expect(parsePayload(body, 'json', undefined, 2, { object_to_records: true })).toHaveLength(2);
  });
});

describe('RSS / Atom parser', () => {
  it('normalizes RSS 2.0 items including georss:point and categories', () => {
    const xml = `<?xml version="1.0"?>
      <rss version="2.0" xmlns:georss="http://www.georss.org/georss">
        <channel><title>Feed</title>
          <item>
            <title>Quake near X</title>
            <link>https://example.org/a</link>
            <description><![CDATA[<p>Strong</p>]]></description>
            <pubDate>Mon, 01 Jan 2024 10:00:00 GMT</pubDate>
            <guid isPermaLink="false">00123</guid>
            <category>hazard</category><category>quake</category>
            <georss:point>45.5 -122.25</georss:point>
          </item>
          <item><title>No geo</title><link>https://example.org/b</link></item>
        </channel>
      </rss>`;
    const r = recs(parsePayload(xml, 'rss'));
    expect(r).toHaveLength(2);
    expect(r[0]).toEqual({
      title: 'Quake near X',
      link: 'https://example.org/a',
      description: '<p>Strong</p>',
      published: '2024-01-01T10:00:00.000Z',
      guid: '00123',
      categories: ['hazard', 'quake'],
      author: null,
      lat: 45.5,
      lon: -122.25
    });
    expect(r[1]).toMatchObject({ guid: 'https://example.org/b', lat: null, lon: null });
  });

  it('reads W3C geo:lat / geo:long', () => {
    const xml = `<rss xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#"><channel>
      <item><title>T</title><guid>g1</guid><geo:lat>10.5</geo:lat><geo:long>20.5</geo:long></item>
      </channel></rss>`;
    expect(recs(parsePayload(xml, 'rss'))[0]).toMatchObject({ lat: 10.5, lon: 20.5 });
  });

  it('normalizes Atom entries (alternate link, id, term categories, gml:pos)', () => {
    const xml = `<feed xmlns="http://www.w3.org/2005/Atom" xmlns:georss="http://www.georss.org/georss" xmlns:gml="http://www.opengis.net/gml">
      <entry>
        <title type="html">Atom item</title>
        <link rel="self" href="https://example.org/self"/>
        <link rel="alternate" href="https://example.org/alt"/>
        <id>urn:uuid:1</id>
        <updated>2024-02-02T02:02:02Z</updated>
        <summary>Sum</summary>
        <author><name>Alice</name></author>
        <category term="news"/>
        <georss:where><gml:Point><gml:pos>1.25 2.5</gml:pos></gml:Point></georss:where>
      </entry>
    </feed>`;
    expect(recs(parsePayload(xml, 'rss'))[0]).toEqual({
      title: 'Atom item',
      link: 'https://example.org/alt',
      description: 'Sum',
      published: '2024-02-02T02:02:02.000Z',
      guid: 'urn:uuid:1',
      categories: ['news'],
      author: 'Alice',
      lat: 1.25,
      lon: 2.5
    });
  });

  it('handles RSS 1.0 (RDF) and returns [] for a non-feed document', () => {
    const rdf = `<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/" xmlns:dc="http://purl.org/dc/elements/1.1/">
      <item><title>R</title><link>https://e/r</link><dc:date>2024-03-03T00:00:00Z</dc:date></item>
    </rdf:RDF>`;
    expect(recs(parsePayload(rdf, 'rss'))[0]).toMatchObject({
      title: 'R',
      published: '2024-03-03T00:00:00.000Z'
    });
    expect(parsePayload('<root/>', 'rss')).toEqual([]);
  });
});

describe('TLE / OMM parsers', () => {
  it('parses 3-line and 2-line element sets and skips stray lines', () => {
    const body = [
      'junk header',
      ...ISS_TLE,
      `0 ${ISS_TLE[0]}`,
      ISS_TLE[1],
      ISS_TLE[2],
      ISS_TLE[1],
      ISS_TLE[2],
      '1 truncated'
    ].join('\r\n');
    const r = recs(parsePayload(body, 'tle'));
    expect(r).toHaveLength(3);
    expect(r[0]).toMatchObject({
      name: 'ISS (ZARYA)',
      norad_id: '25544',
      intl_designator: '98067A',
      inclination: 51.6416,
      eccentricity: 0.0006703,
      mean_motion: 15.72125391,
      line1: ISS_TLE[1],
      line2: ISS_TLE[2]
    });
    expect(String(r[0].epoch)).toMatch(/^2008-09-20T12:25:40/);
    expect(r[1].name).toBe('ISS (ZARYA)'); // "0 " prefix stripped
    expect(r[2].name).toBe('NORAD 25544'); // 2-line set
  });

  it('caps element sets with max_records', () => {
    const body = [...ISS_TLE, ...ISS_TLE, ...ISS_TLE].join('\n');
    expect(parsePayload(body, 'tle', undefined, 2)).toHaveLength(2);
  });

  it('computes TLE checksums', () => {
    expect(tleChecksum(ISS_TLE[1])).toBe(7);
    expect(tleChecksum(ISS_TLE[2])).toBe(7);
  });

  it('synthesizes a byte-identical TLE from OMM mean elements', () => {
    expect(ommToTle(ISS_OMM)).toEqual({ line1: ISS_TLE[1], line2: ISS_TLE[2] });
    expect(ommToTle({ ...ISS_OMM, MEAN_MOTION: undefined })).toBeNull();
    expect(ommToTle({ ...ISS_OMM, EPOCH: 'bad' })).toBeNull();
  });

  it('parses CelesTrak GP JSON (omm_json), keeping OMM fields', () => {
    const r = recs(parsePayload(JSON.stringify([ISS_OMM, { OBJECT_NAME: 'broken' }]), 'omm_json'));
    expect(r).toHaveLength(1);
    expect(r[0]).toMatchObject({
      name: 'ISS (ZARYA)',
      norad_id: '25544',
      intl_designator: '1998-067A',
      OBJECT_NAME: 'ISS (ZARYA)',
      line1: ISS_TLE[1],
      line2: ISS_TLE[2]
    });
  });
});
